// Mock data for Discord Moderation Dashboard

export const serverStats = {
  totalMembers: 24589,
  onlineMembers: 8432,
  newMembersToday: 156,
  messagesDeleted: 342,
  warningsIssued: 28,
  bansToday: 5,
  activeModerators: 12,
  serverHealth: 94,
}

export const moderationActivity = [
  { date: "Jan 17", warnings: 45, bans: 8, mutes: 23, deletions: 120 },
  { date: "Jan 18", warnings: 38, bans: 5, mutes: 19, deletions: 98 },
  { date: "Jan 19", warnings: 52, bans: 12, mutes: 31, deletions: 145 },
  { date: "Jan 20", warnings: 41, bans: 6, mutes: 22, deletions: 112 },
  { date: "Jan 21", warnings: 35, bans: 4, mutes: 18, deletions: 87 },
  { date: "Jan 22", warnings: 48, bans: 9, mutes: 27, deletions: 134 },
  { date: "Jan 23", warnings: 28, bans: 5, mutes: 15, deletions: 89 },
]

export const recentActions = [
  {
    id: "1",
    type: "ban",
    user: { name: "toxicplayer99", avatar: "T", id: "123456789" },
    moderator: { name: "AdminSteve", avatar: "A" },
    reason: "Repeated harassment and hate speech",
    timestamp: "2 minutes ago",
    channel: "#general",
  },
  {
    id: "2",
    type: "warn",
    user: { name: "newbie_2024", avatar: "N", id: "234567890" },
    moderator: { name: "ModSarah", avatar: "M" },
    reason: "Spamming promotional links",
    timestamp: "15 minutes ago",
    channel: "#promotions",
  },
  {
    id: "3",
    type: "mute",
    user: { name: "angryuser", avatar: "A", id: "345678901" },
    moderator: { name: "AutoMod", avatar: "🤖" },
    reason: "Excessive caps usage (Auto-detected)",
    timestamp: "32 minutes ago",
    channel: "#off-topic",
    duration: "30 minutes",
  },
  {
    id: "4",
    type: "delete",
    user: { name: "suspicious_link", avatar: "S", id: "456789012" },
    moderator: { name: "AutoMod", avatar: "🤖" },
    reason: "Malicious link detected",
    timestamp: "1 hour ago",
    channel: "#links",
  },
  {
    id: "5",
    type: "kick",
    user: { name: "rulebreaker22", avatar: "R", id: "567890123" },
    moderator: { name: "ModJake", avatar: "J" },
    reason: "Ignoring multiple warnings",
    timestamp: "2 hours ago",
    channel: "#voice-chat",
  },
  {
    id: "6",
    type: "warn",
    user: { name: "capslock_king", avatar: "C", id: "678901234" },
    moderator: { name: "ModSarah", avatar: "M" },
    reason: "Excessive use of caps lock",
    timestamp: "3 hours ago",
    channel: "#gaming",
  },
]

export const bannedUsers = [
  {
    id: "1",
    name: "toxicplayer99",
    odId: "123456789012345678",
    avatar: "T",
    reason: "Repeated harassment and hate speech",
    bannedBy: "AdminSteve",
    bannedAt: "Jan 23, 2026 - 10:32 AM",
    appealStatus: "pending",
  },
  {
    id: "2",
    name: "spammer_bot_v2",
    odId: "234567890123456789",
    avatar: "S",
    reason: "Automated spam bot activity",
    bannedBy: "AutoMod",
    bannedAt: "Jan 22, 2026 - 8:15 PM",
    appealStatus: "denied",
  },
  {
    id: "3",
    name: "raid_leader_x",
    odId: "345678901234567890",
    avatar: "R",
    reason: "Organizing server raid",
    bannedBy: "AdminSteve",
    bannedAt: "Jan 21, 2026 - 3:45 PM",
    appealStatus: "none",
  },
  {
    id: "4",
    name: "nsfw_poster",
    odId: "456789012345678901",
    avatar: "N",
    reason: "Posting NSFW content in SFW channels",
    bannedBy: "ModSarah",
    bannedAt: "Jan 20, 2026 - 11:20 AM",
    appealStatus: "approved",
  },
  {
    id: "5",
    name: "scammer_123",
    odId: "567890123456789012",
    avatar: "S",
    reason: "Attempting to scam members",
    bannedBy: "ModJake",
    bannedAt: "Jan 19, 2026 - 6:30 PM",
    appealStatus: "pending",
  },
]

export const autoModRules = [
  {
    id: "1",
    name: "Anti-Spam Filter",
    description: "Detects and removes spam messages",
    enabled: true,
    triggers: 1245,
    lastTriggered: "5 minutes ago",
    action: "delete + warn",
  },
  {
    id: "2",
    name: "Link Protection",
    description: "Blocks suspicious and malicious links",
    enabled: true,
    triggers: 892,
    lastTriggered: "1 hour ago",
    action: "delete + mute",
  },
  {
    id: "3",
    name: "Profanity Filter",
    description: "Filters out profanity and slurs",
    enabled: true,
    triggers: 3421,
    lastTriggered: "12 minutes ago",
    action: "delete",
  },
  {
    id: "4",
    name: "Caps Lock Control",
    description: "Limits excessive caps usage",
    enabled: true,
    triggers: 567,
    lastTriggered: "32 minutes ago",
    action: "warn",
  },
  {
    id: "5",
    name: "Mention Spam",
    description: "Prevents mass mentions",
    enabled: true,
    triggers: 234,
    lastTriggered: "2 hours ago",
    action: "mute",
  },
  {
    id: "6",
    name: "Invite Link Blocker",
    description: "Blocks Discord server invite links",
    enabled: false,
    triggers: 89,
    lastTriggered: "1 day ago",
    action: "delete + warn",
  },
]

export const moderators = [
  {
    id: "1",
    name: "AdminSteve",
    avatar: "A",
    role: "Administrator",
    status: "online",
    actionsToday: 45,
    actionsThisWeek: 234,
    joinedAt: "Mar 2023",
  },
  {
    id: "2",
    name: "ModSarah",
    avatar: "M",
    role: "Senior Moderator",
    status: "online",
    actionsToday: 38,
    actionsThisWeek: 189,
    joinedAt: "Jun 2023",
  },
  {
    id: "3",
    name: "ModJake",
    avatar: "J",
    role: "Moderator",
    status: "idle",
    actionsToday: 22,
    actionsThisWeek: 145,
    joinedAt: "Sep 2023",
  },
  {
    id: "4",
    name: "HelperAlex",
    avatar: "H",
    role: "Trial Moderator",
    status: "online",
    actionsToday: 15,
    actionsThisWeek: 67,
    joinedAt: "Dec 2025",
  },
  {
    id: "5",
    name: "NightOwl",
    avatar: "N",
    role: "Moderator",
    status: "offline",
    actionsToday: 0,
    actionsThisWeek: 112,
    joinedAt: "Aug 2023",
  },
]

export const warningLevels = [
  { level: 1, count: 456, action: "Verbal warning" },
  { level: 2, count: 234, action: "24h mute" },
  { level: 3, count: 89, action: "7 day mute" },
  { level: 4, count: 34, action: "Kick" },
  { level: 5, count: 12, action: "Permanent ban" },
]

export const channelActivity = [
  { name: "#general", messages: 12450, modActions: 89, risk: "low" },
  { name: "#off-topic", messages: 8923, modActions: 156, risk: "medium" },
  { name: "#gaming", messages: 6789, modActions: 45, risk: "low" },
  { name: "#music", messages: 4567, modActions: 23, risk: "low" },
  { name: "#politics", messages: 3456, modActions: 234, risk: "high" },
  { name: "#memes", messages: 9876, modActions: 178, risk: "medium" },
]

export const memberGrowth = [
  { date: "Jan 17", members: 23890, joins: 234, leaves: 45 },
  { date: "Jan 18", members: 24079, joins: 256, leaves: 67 },
  { date: "Jan 19", members: 24268, joins: 189, leaves: 78 },
  { date: "Jan 20", members: 24312, joins: 178, leaves: 34 },
  { date: "Jan 21", members: 24398, joins: 145, leaves: 59 },
  { date: "Jan 22", members: 24489, joins: 167, leaves: 76 },
  { date: "Jan 23", members: 24589, joins: 156, leaves: 56 },
]

export const servers = [
  {
    id: "1",
    name: "Gaming Hub",
    icon: "🎮",
    members: 24589,
    health: 94,
  },
  {
    id: "2",
    name: "Tech Talk",
    icon: "💻",
    members: 15234,
    health: 87,
  },
  {
    id: "3",
    name: "Art Community",
    icon: "🎨",
    members: 8956,
    health: 98,
  },
]
